version: '3.9'

services:
  api-service:
    build: ./api-service
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    volumes:
      - ./log_generator/log:/app/log

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
    depends_on:
      - api-service
